
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := wl127x-fw-4-plt
LOCAL_SRC_FILES := wl127x-fw-4-plt.bin
LOCAL_MODULE_SUFFIX := .bin
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/ti-connectivity
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := wl127x-fw-4-sr
LOCAL_SRC_FILES := wl127x-fw-4-sr.bin
LOCAL_MODULE_SUFFIX := .bin
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/ti-connectivity
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := wl1271-nvs
LOCAL_SRC_FILES := wl1271-nvs.bin
LOCAL_MODULE_SUFFIX := .bin
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/ti-connectivity
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := wl127x-fw-4-mr
LOCAL_SRC_FILES := wl127x-fw-4-mr.bin
LOCAL_MODULE_SUFFIX := .bin
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/ti-connectivity
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := TQS_S_2.6
LOCAL_SRC_FILES := TQS_S_2.6.ini
LOCAL_MODULE_SUFFIX := .ini
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/wifi
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := TQS_D_1.7
LOCAL_SRC_FILES := TQS_D_1.7.ini
LOCAL_MODULE_SUFFIX := .ini
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/wifi
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := TIInit_7.2.31
LOCAL_SRC_FILES := TIInit_7.2.31.bts
LOCAL_MODULE_SUFFIX := .bts
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := hci_vhci
LOCAL_SRC_FILES := hci_vhci.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := lib80211
LOCAL_SRC_FILES := lib80211.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := cfg80211
LOCAL_SRC_FILES := cfg80211.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := wl12xx_sdio_test
LOCAL_SRC_FILES := wl12xx_sdio_test.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := btsdio
LOCAL_SRC_FILES := btsdio.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := scsi_wait_scan
LOCAL_SRC_FILES := scsi_wait_scan.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := hci_uart
LOCAL_SRC_FILES := hci_uart.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := mac80211
LOCAL_SRC_FILES := mac80211.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := wl12xx
LOCAL_SRC_FILES := wl12xx.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := bluetooth
LOCAL_SRC_FILES := bluetooth.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := tty_hci
LOCAL_SRC_FILES := tty_hci.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := compat
LOCAL_SRC_FILES := compat.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := btwilink
LOCAL_SRC_FILES := btwilink.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := rfcomm
LOCAL_SRC_FILES := rfcomm.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := bnep
LOCAL_SRC_FILES := bnep.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := hidp
LOCAL_SRC_FILES := hidp.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := wl12xx_sdio
LOCAL_SRC_FILES := wl12xx_sdio.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := gps_drv
LOCAL_SRC_FILES := gps_drv.ko
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_OWNER := ti
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)

